# Generated by Django 6.0.2 on 2026-04-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huggingface_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(default='mistralai/Mistral-7B-Instruct-v0.3', help_text='Hugging Face model ID for text generation', max_length=255)),
                ('system_prompt', models.TextField(default='You are SwiftConnect AI, a friendly and helpful assistant built into the SwiftConnect messaging app. You can help with questions, writing, coding, math, creative tasks, and general knowledge. Keep your responses concise, helpful, and conversational. Use markdown formatting when appropriate for code blocks and lists.', help_text='System prompt that defines the bot personality')),
                ('max_history_messages', models.IntegerField(default=20, help_text='Maximum number of past messages to include as context')),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.botconversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
