# Generated by Django 6.0.4 on 2026-04-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='model_name',
            field=models.CharField(default='meta-llama/Meta-Llama-3-8B-Instruct', help_text='Hugging Face model ID for text generation', max_length=255),
        ),
    ]
