# Generated by Django 6.0.2 on 2026-04-26 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_status_notification_statuslike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_participants',
            field=models.ManyToManyField(blank=True, related_name='hidden_in_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
