# Generated by Django 6.0.2 on 2026-04-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversationsetting_advanced_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsetting',
            name='is_study_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
