# Generated by Django 6.0.2 on 2026-04-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversationsetting_is_study_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsetting',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
