# Generated by Django 6.0.4 on 2026-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_lock_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
