# Generated by Django 6.0.2 on 2026-04-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='study_mode_active',
            field=models.BooleanField(default=False),
        ),
    ]
